### ISSUE TITLE
[Question] SonataAdmin requires extended ->add()

### ISSUE THREAD

**Issue by drAlberT** [fre5h/DoctrineEnumBundle#28]
Hello,
  I have implemented a new type and it works perfectly but in the form generated by the entity admin of  Sonata Admin Bundle I have to use the extended `->add()` form to have all working otherwise it did not recognise the field type as a choice, if I force the second parameter as `choice` the select is empty .. specifying every parameter makes everything work as a charm 

```
   use FooBundle\DBAL\Types\MyFooType

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('user')
            ->add('date', 'sonata_type_date_picker')
            ->add('myfoo', 'choice', array('label' => 'Foo', 'choices' => MyFooType::getChoices()))
        ;
    }
```

Am I wrong in something or is it normal? 

Thank you in advance

```
sonata-project/admin-bundle              dev-master 718c5aa
sonata-project/doctrine-orm-admin-bundle dev-master 6299bc8
fresh/doctrine-enum-bundle               v3.2
symfony/symfony                          v2.7.0
PHP 5.4.41-0+deb7u1 (cli) (built: May 28 2015 18:22:26)
```

**Comment by fre5h** [comment]
Try just `->add('lv_mv')` there is a type guesser, it works for me in my projects

**Comment by drAlberT** [comment]
???

As I said it seems the guesser did not work for me ..  I **have** to use the extended format of add() otherwise it did not work :( 

May be something related to sonata/symfony versions?

**Comment by fre5h** [comment]
Maybe. I didn't check it with symfony 2.7 and the latest sonata. I will invesigate this case

**Comment by drAlberT** [comment]
Thank you so much .. meanwhile I'll leave the extended format :)

**Comment by fre5h** [comment]
@drAlberT I have updated one of my projects to the version of Symfony 2.7 and your version of Sonata. Then I checked my ENUM fields in Sonata admin and they still work.

Did you read upgrade guide to Symfony 2.7. There is a change:
https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md

> You should flip the keys and values of the "choices" option in ChoiceType and set the "choices_as_values" option to `true`. The default value of that option will be switched to `true` in Symfony 3.0.

Before:

   ```php
   $form->add('status', 'choice', array(
       'choices' => array(
           Status::ENABLED => 'Enabled',
           Status::DISABLED => 'Disabled',
           Status::IGNORED => 'Ignored',
       )),
   ));
   ```

   After:

   ```php
   $form->add('status', 'choice', array(
       'choices' => array(
           'Enabled' => Status::ENABLED,
           'Disabled' => Status::DISABLED,
           'Ignored' => Status::IGNORED,
       ),
       'choices_as_values' => true,
       // important if you rely on your option value attribute (e.g. for JavaScript)
       // this will keep the same functionality as before
       'choice_value' => function ($choice) {
           return $choice;
       },
   ));
```

But this old version of `choice` still works, it is just depracated and will be remove in 3.0. So the one idea why guesser doesn't work for you is that you used the new `choice` syntax of Symfony 2.7 and you flipped keys and values. But in this case it should also return some values for your select field in Sonata.

Otherwise, check my example and then check if in your code keys and values are on same places.
```php
class BasketballPositionType extends AbstractEnumType
{
    const POINT_GUARD    = 'PG';
    const SHOOTING_GUARD = 'SG';
    const SMALL_FORWARD  = 'SF';
    const POWER_FORWARD  = 'PF';
    const CENTER         = 'C';

    protected static $choices = [
        self::POINT_GUARD    => 'Point guard',
        self::SHOOTING_GUARD => 'Shooting guard',
        self::SMALL_FORWARD  => 'Small forward',
        self::POWER_FORWARD  => 'Power forward',
        self::CENTER         => 'Center'
    ];
}
```

And the last thing. Check the source code https://github.com/fre5h/DoctrineEnumBundle/blob/master/Form/EnumTypeGuesser.php#L57
There are 4 returns. Three of them return `null`.

* If no metadata for this class
* If it is not one of the registered ENUM types
* If it is not a child of `AbstractEnumType`

Check if you haven't any of this problem with your ENUM class.

Fourth `return` returns guessed type depends on parameters. Debug this row https://github.com/fre5h/DoctrineEnumBundle/blob/master/Form/EnumTypeGuesser.php#L99 and check what data is in `$parameters`.

**Comment by drAlberT** [comment]
Hi @fre5h .. thanks for your time ..

I'm doing some tests and I stumbled again a strange behaviour .. I think I'm doing something stupid, but I can't argue what .. so please be patient :)

**I intentionally introduced a parse error in the `EnumTypeGuesser`** .. but in the Edit action of sonata admin I have **no errors** .. so my guess is that the `EnumTypeGuesser` is not being invoked at all ... is it possible? How can I debug better?

(BTW, my type code follows your example and keys and values are on the same place) 

Thank you

**Comment by drAlberT** [comment]
OK solved

        // This is not one of the registered ENUM types
        if (!isset($this->registeredEnumTypes[$fieldType])) {
            return null;

I was using a "type name" different from the class name .. but the check impose that they are identical .. 

Please add a caveat on the doc :)  

Thank you for your time
