### ISSUE TITLE
Class-less annotation-based enum values

### ISSUE THREAD

**Issue by ABM-Dan** [fre5h/DoctrineEnumBundle#42]
Would it be possible to have the list of values defined in an annotation and have a generic enum class managing it generically? 

We are indeed creating a bunch of classes that have nothing but arrays of data (on average cases).

**Comment by fre5h** [comment]
I think it is possible to set a list of values for ENUM in annotation. But how do you want to set this values in your code? Do you want use just strings for it?
```php
// Like
$order->setStatus('paid');
// instead of
$order->setStatus(OrderStatusType::PAID);
```

Because when you have an EnumClass for your type, then you have all values placed in one class and when you need to change the value you can easily do it

```php
final class OrderStatusType extends AbstractEnumType
{
    const PAID = 'your_new_value';
}
```

And with string you can have problems if you forget to update it in some place.

So if you want to have something like this

```php
class User
{
    /**
     * @ORM\Column(type="ENUM", nullable=false)
     * @DoctrineAssert\Enum(values={'male', 'female'})
     */
    private $gender;
```

If think it can be implemented via annotation, but I don't see any benefit for it.

**Comment by ABM-Dan** [comment]
Yes, strings would work.

What you are describing are not drawbacks of the implementation, they are drawbacks of the ENUM type, and while it kinda sucks that there have to be drawbacks, that's the price to pay to avoid 1-n relations with very small and underused tables.

I'm not suggesting this to be the default, but it could be a relevant option.

It does indeed have points of failure, but they coincide with the ones you get from using an ENUM in the first place, and should therefore be acceptable.

**Comment by fre5h** [comment]
Maybe just set your field to string instead of enum and add simple validator for allowed values? :)

**Comment by ABM-Dan** [comment]
But the idea was that then you could have the annotation be filled in by doctrine tools/the database schema would be updated from the annotation. All of this is so I can have the entity entirely defined in one space (for entities that are not crazy complex), and still be able to leverage the automation of Symfony.

**Comment by fre5h** [comment]
I understood your point of view. But at the near future I won't have time to implement it, so if you want you can try to implement it and we will see what we get in the result.

**Comment by fre5h** [comment]
Isn't actual
