### ISSUE TITLE
SET version

### ISSUE THREAD

**Issue by ph-il** [fre5h/DoctrineEnumBundle#85]
Might be interesting to have a set version like : https://github.com/okapon/DoctrineSetTypeBundle

**Comment by fre5h** [comment]
What exactly do your propose?

**Comment by fre5h** [comment]
@ph-il ping

**Comment by ph-il** [comment]
There code is quite near yours. Except, it's not up to date and there is no response from them. 

Maybe having a DoctrineSetBundle base on your bundle or add Set this this one.

**Comment by fre5h** [comment]
How often do you use SETs in MySQL? After I studied at university I have never used sets in databases. One of the reason not to use them is that it is an anti-pattern. You can use many-to-many relations instead of sets. Another one is that sets are not widely used in other RDBMS and their implementation is different.
One more thing is that a lot of developers are migrating to NoSQL databases, so on the SQL-related databases stay only those who need ACID.
That's why I didn't implement DoctrineSetBundle next after DoctrineEnumBundle. I think there are better ways to show your relations in database, or choose another database. But I am not against of it. If somebody has already implemented it, that's fine.
